### ISSUE TITLE
Create a better/safer way to store API keys

### ISSUE THREAD

**Issue by igordutra** [lucasfr/weatherFeelings#3]
Create secrets.py file

* Commit initial version with dummy or XXX keys
* add to .gitignore
* import

**Comment by igordutra** [comment]
@lucasfr Pega ai sua tarefa :)
Tem que colocar a versao inicial do secrets.py com dummy keys ou 'XXX' senao ninguem vai saber como criar.

We should be writing in english.

**Comment by lucasfr** [comment]
I just don't want to replace the at every pull... :/
Will think about a smart way to do this.
